### ISSUE TITLE
Add "Video" as a category when uploading documents to MY Community

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#126]
What would it take to add "Video" as a category when uploading items to MY Community? We'd need it on both the user and admin sides.

**Comment by bguerrettaz** [comment]
Probably just 2 hours.

Please keep in mind that videos are larger files.  Right now there is an
upload limit of 10MB, which isn't a very large video (depending on the
quality and the format).

Also, when uploading a file 5MB or larger, the user will just 'sit' on the
screen until its done uploading.  You might want to think about placing a
loading image while the image is uploading.

Just my 2cents.

Blake

**Comment by dpentony** [comment]
Actually, I would like to encourage that they list only links for videos already hosted on other sites. I do not think many teachers would have their own videos. Perhaps we could call the category "Video Links". Is there some language we could use to make it obvious that we want them to upload links instead of the actual video files?

**Comment by bguerrettaz** [comment]
Ok, currently MyCommunity requires a file upload.  We would have to change
some things in different spots to allow a video link in place of an actual
file.  Then add that category and a textbox for the URL.

We would also have to account for the search functionality, because right
now, its looking for a file/filename.  In this case, it would have to look
for a video link, etc.

I'd also have to change the database table a little to add those fields.

**Comment by dpentony** [comment]
Thanks. I think we'll keep it as is for now.

**Comment by bguerrettaz** [comment]
Ok, sounds good.  If you decide to in the future, I could probably get it done in 8-10 hours.

Blake
