### ISSUE TITLE
Adding a Math Common Core Standard - brings an error message

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#129]
I have a few new Math Common Core Anchor Standards that I need to enter and when I try to do this, I get the following error message:

Microsoft OLE DB Provider for ODBC Drivers error '80004005'

[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

/admin/Lesson-Library/Common-Core/Math/AddAnchorStd.asp, line 300

**Comment by dpentony** [comment]
Any progress on this? We are at a standstill.

**Comment by bguerrettaz** [comment]
I will look into this now.

**Comment by bguerrettaz** [comment]
Should be good to go.  Please retry

**Comment by mnichols13** [comment]
While the add a new anchor standard works, the issue is that the edit/delete function does not work.  

This is the only way I have of reviewing the standards that have already been entered to ensure that I have the correct one.

**Comment by bguerrettaz** [comment]
This is also fixed.

This is due to these pages having older style connection strings and when
upgrading to new servers or new versions of SQL server, they have to be
rewritten.

Here is an example:

Old:
set conn = server.CreateObject("adodb.connection")
conn.open "MyCAERT", "------", "------"

New:
set conn = server.CreateObject("adodb.connection")
cst="Provider=SQLOLEDB;Password=----------;Persist Security Info=True;User
ID=--------;Data Source=216.224.165.22;Initial Catalog=csat2"
conn.open cst

If you encounter more issues like this, please let me know.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good thanks.

**Comment by mnichols13** [comment]
Re-opening this issue  because I cannot view the broad standards for the English Common Core through the edit/delete function here is the error message that I get:

Microsoft OLE DB Provider for ODBC Drivers error '80004005'

[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

/admin/Lesson-Library/Common-Core/English/SelectAnchorStd.asp, line 242

 
Edit Anchor Standard

Use helpful filters to quickly find the Anchor Standard you are looking for:

**Comment by mnichols13** [comment]
So the same thing happens for Science:

Microsoft OLE DB Provider for ODBC Drivers error '80004005'

[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

/admin/Lesson-Library/Common-Core/Science/SelectAnchorStd.asp, line 242

 
Edit Anchor Standard

Use helpful filters to quickly find the Anchor Standard you are looking for:

**Comment by bguerrettaz** [comment]
I missed these in the move to the new server.  I checked directories, but
this one got overlooked.

I've searched the entire directory structure for this type of connection
string and replaced all (this is a unique connection string, which is why
is was missed).

I won't charge for this one since I missed it.

Please test and confirm these changes.

Blake

**Comment by mnichols13** [comment]
looks good - thanks for doing this so quick!
