### ISSUE TITLE
Embed an Audio File into a Test Question?

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#132]
Could there be a feature to allow a teacher to embed an audio recording of the question for those special ed students who need the test read to them? What would it cost to add such functionality?

**Comment by BrianPeterlin** [comment]
This function works in Internet Explorer 8 and but it does not appear to work in Chrome.  Do you think we need to build a chrome compatible method?

![image](https://cloud.githubusercontent.com/assets/5776485/6675552/315da872-cbef-11e4-84c0-7184463aa137.png)

**Comment by dpentony** [comment]
Based on Google Analytics (see below) close to 70% of users use Chrome. So, yes, we'd like to get a price to build a Chrome compatible method.

![image](https://cloud.githubusercontent.com/assets/5790325/6676773/6cc36858-cbf8-11e4-9287-66dd53ca64e3.png)

**Comment by bguerrettaz** [comment]
Here is the estimate breakdown for this request.  Please let Brian or I
know if you have any questions.

To add audio (that is usable across browsers) we need to append certain
HTML onto the HTML produced out of the question editor.  By doing this, it
creates a seamless way for the quizzes to be placed in the browsers without
any actual code changes to the quizzes themselves.

We do have to create a storage mechanism for the audio files and a database
table to track and relate to a certain question.

Because there are complexities with appending the HTML to the existing
HTML, plus testing some of this out, the estimate for this would be 20-40
hours.  It is a rough estimate based on it could be on the lower end if all
goes the way I hope it will, but like anything, there are always factors
that come into play that I didn't expect or see in the estimate phase.

Please let me know what questions you have.

Blake

**Comment by dpentony** [comment]
Thanks for the info. We will take it under consideration and close this issue out for now. Much of what we choose to do in the future will be determined by what happens with the CTE and Ag line items in the new Illinois budget.
