### ISSUE TITLE
URGENT - NJ Statewide Test Issue

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#138]
New Jersey has a statewide test set up called 2015 Meat Evaluation CDE Identification. When logged in as teacher Erin Noble, question #3 displays fine. See first screenshot below. However, when logged in as a student who is set up to take the test (Emily Karr), that question does not show up. The student view skips displaying the question and then renumbers the rest of the questions.

This is urgent as they are trying to give the test.

![image](https://cloud.githubusercontent.com/assets/5790325/6829095/44703a50-d2df-11e4-931e-09c59f1a0cb9.png)

![image](https://cloud.githubusercontent.com/assets/5790325/6829155/8cb081a8-d2df-11e4-895b-84a6fcdac2c2.png)

**Comment by bguerrettaz** [comment]
I sent the below yesterday:

---------


On this issue, I logged in as that teacher, activated the quiz, opened the quiz as student: dummy 1 and the question displayed fine for me.

I also tried preview quiz and print quiz and it showed up everywhere.

Did I miss a step?

**Comment by BrianPeterlin** [comment]
To be honest, I think this is an outlier.  Probably something with the HTML produced from the questions/pictures that are a part of the quiz plus the HTML because they met their max submissions.

Since we haven't encountered this in the past, I would call this an anomaly.

Let me know if you want me to do anything else with this issue.

Thanks,
Blake

On Fri, Mar 27, 2015 at 1:55 PM, Dan Pentony <dpentony@caert.net> wrote:
One thought, Could the problem with the quiz relate to the fact that they used almost all of the same questions from previous year’s quizzes?
