### ISSUE TITLE
Hiding of Old IL Learning Standards

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#167]
When we first developed the lesson plans, we were aligning them to the IL learning Standards. These standards have been replaced by the new Common Core Standards. What would it take to hide the alignments to the old IL Learning Standards? We'd need to hide the alignments for Math, English, and Social Studies. See highlight in screenshot below.

![image](https://cloud.githubusercontent.com/assets/5790325/10124379/af8b7f76-6519-11e5-927b-364d5410ce51.png)

**Comment by bguerrettaz** [comment]
Did you not want to pursue this one?

**Comment by dpentony** [comment]
Need an estimate.

**Comment by bguerrettaz** [comment]
So you would want to remove the highlighted part from the course outline?
So it would be 'Learning Standards' and the standards right below that?

Just need clarification.

Thanks,
Blake

**Comment by dpentony** [comment]
We would only want to hide the Math, English and Social Studies standards that would appear in the highlight area. See on Admin page under Maintain IL >> Lesson to Learning area. We want to hide alignments to ELA, MA, & SS. Remember, we don't want to delete them but just hide them. Just an estimate is needed at this point.

![image](https://cloud.githubusercontent.com/assets/5790325/10337729/5e289870-6cc7-11e5-880f-d4ca5ad2812d.png)

**Comment by bguerrettaz** [comment]
Ok, for that to occur, I would need to add columns to the database tables,
probably a field called 'Hidden' and a value of Y or N.  Through the admin
console, I would build an interface to be able to hide any of these, if you
wanted, otherwise, I could do it anytime you wanted to hide anything else.

The real time comes into what uses those values, for example, the course
outline, among other things I'm sure.  I would have to change those queries
to not show records with a 'Hidden' value of 'Y'.  If it was 'Y', then it
would be hidden from view.

I'm not exactly sure every spot those standards are used, but I'm guessing
quite a few places.

Here's the breakdown I have come up with for this:

- Add database column to standards table (3-4 hours)
- Build admin interface to change standards from hidden to viewable or vice
versa (this is optional as we could do it if it wasn't a high occurrence)
(6-7 hours)
- Change queries on pages that use these standards (1-2 hours per page)

If you just care about hiding from the saved course outline view, you're
looking at 4-6 hours without the admin interface.  We could always do it in
phases as well (as we find pages, make the changes).

Please let me know your thoughts.

Blake

**Comment by dpentony** [comment]
Thanks. This is a special request by ISBE. I will need to provide the cost to them to see if they want to proceed.

**Comment by bguerrettaz** [comment]
Sounds good, thanks.

**Comment by bguerrettaz** [comment]
Just checking the status on this to see if you wanted to move forward or if you're waiting for more feedback?

Thanks,
Blake

**Comment by dpentony** [comment]
I have provided a quote to ISBE and am awaiting their response. With the budget woes, this will not happen quickly.

**Comment by dpentony** [comment]
@bguerrettaz  - could we schedule a time to talk later this week? I've got a few questions on this and thought a phone conversation would be most efficient.

**Comment by bguerrettaz** [comment]
Sure thing.  I'm traveling on business to Philadelphia until Thursday
afternoon.  Would a call around 4pm on Thursday work?

Blake

**Comment by dpentony** [comment]
Yes. Please give me a call on Thursday.

**Comment by bguerrettaz** [comment]
Ok, I did some more research on this.  Here is what I've found:

-These tables are in a separate database, ILMatrix_v2, which controls the learning standards, etc.  
-There are many tables aligned with those dropdowns, which means we would have to identify the state goals, learning standards, and learning benchmarks to the ones we want to remove/archive.
-This can be done.  To archive the tables (all) roughly 2 hours, then to remove the rows needed would be another 3-4 hours.
-Once I have removed the identified rows, I would need you and Mindy to validate that ones aren't missing and that there aren't any that still aren't supposed to be there.

I estimated above that it would be 4-6 hours (at a minimum) to build a column then resulting logic on each page that uses those to filter out hidden rows.  I now think that is more like 10 hours based on what I learned.

Since you stated that you didn't think these would be needed again, a simple archive and remove seems like the best option.

Please let me know your thoughts.

Thanks,
Blake

**Comment by dpentony** [comment]
I will share this new info with ISBE and get back to you. It may be a while....
