### ISSUE TITLE
Views on a Quiz not defaulting as stated

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#183]
We had a teacher contact us with suspected cheating.  As we were investigating how this might have happened, it was discovered that one student viewed the quiz three times.   On our parameters page, the views should default to the number of submits if the box is left blank.  That is what our information states next to the box.  This particular quiz was set to one submission so no student should have had the opportunity to view it more than once.   

We need to get this fixed to prevent students from viewing quizzes multiple times when the teachers do not want them to be able to.

**Comment by dpentony** [comment]
As a result of this glitch, the teacher (Jay Williams in IL) thinks some cheating may have gone on with a test called Corn and Soybeans 1A. He thinks that a student by the name of Kane Vanbriesen was able to View the test more than once. It looks like he logged in during the period from about 8:30 to 9:30 AM on 12.4.15. The teacher has asked if we can identify the IP address those two login instances came from. If it was two different addresses, it would help him in his efforts. Can we provide the IP addresses for the two login instances of Kane Vanbriesen when he accessed the Carn and Soybeans 1A test?

**Comment by bguerrettaz** [comment]
Two things:

- The defaulting was not working correctly.  I have fixed the issues (in two places) and tested the fix.  If the number of views is left blank, it will default to the number of submissions, otherwise it will use the value in the number of views box.

- We do not currently track or log the IP address of the user, in this case, the student taking the quiz.  To track this sort of thing, in case of cheating or other issues, it would be a good idea to put this type of logging in.  Let me know if you want more details.

Please test and confirm the fix I put in place.

Thanks,
Blake

**Comment by dpentony** [comment]
When a teacher chooses Submit Once Per Day under submissions on the parameters page, the field for the views page remains blank. When you update the quiz, you get this error message: 

SOPD
Microsoft OLE DB Provider for SQL Server error '80040e14'

Invalid column name 'SOPD'.

/Teachers/csat/EditQuizParameters_Update.asp, line 309

**Comment by dpentony** [comment]
We also get an error message if the number of views allowed is set to "other". There is supposed to be an integer in the views allowed field, but when the submissions are set and an integer is entered, the views field shows "other" without an integer. See screen shot below:

![image](https://cloud.githubusercontent.com/assets/5790325/11690687/7b3a586e-9e5d-11e5-8516-1bfc3855e444.png)

If they try to change the date on a quiz, they get the following error message:

other
Microsoft OLE DB Provider for SQL Server error '80040e14'

Invalid column name 'other'.

/Teachers/csat/EditQuizParameters_Update.asp, line 309

However, if they FIRST change the views to an integer, save the change, and then change the date parameter it works. So, the issue has to do with "other" and not an integer appearing in the views field.

I am not sure how "other" can appear in the views field. If I attempt to change the submissions parameter to "other" I'm forced to enter an integer. That integer defaults to the views field. So, I'm not sure how "other" (instead of an integer) got in that field as shown in the above screenshot.

The fact that the integer value in the submissions field did not default to the views field might have been an issue BEFORE you made the latest change. Essentially, you may have corrected an issue we didn't know we had. Two teachers have contacted us about the "other" error message. The issue may have already been corrected and there is no fix to this. We just need to tell the teachers to enter an integer instead of "other" into the view field.

**Comment by bguerrettaz** [comment]
I am almost completed with this issue.  There were a few issues with this.

Blake

**Comment by bguerrettaz** [comment]
Ok, I have completed all of the changes needed and tested each scenario.

Please test and confirm and let me know of any issues.

Blake
