### ISSUE TITLE
Glitch in Quiz Scores

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#190]
Kevin Garling in Indiana gave a quiz Hort Growing Media 030020 in his Hort 15 course.

Ashley Dutro took the quiz three times.    Mycaert shows she submitted it five times. 

Her scores were reported as:
0/1
0/1
11/15
24/30
24/30

There were only 15 questions worth one point each.  

Why would the system report the scores as 24/30 with only 15 possible?

**Comment by bguerrettaz** [comment]
I'll look into this and report back.

Blake

**Comment by dpentony** [comment]
We may have had a similar issue with him before.

**Comment by bguerrettaz** [comment]
I looked into this and wasn't able to actually recreate, but do see
something weird in the data.

These scores are calculated by something called a submission counter.
There are submissions 4 and 5, but each 4 and 5 have double the
submissions, at different timestamps:

For submission 4 - 2016-03-11 20:58:36.820 & 2016-03-13 19:25:14.553
For submission 5 - 2016-03-13 19:28:54.270 & 2016-03-15 09:36:35.953

Each submission should only have ONE timestamp, not two.  This would
explain why the grading is double counted, but I'm not sure how it happened
in the first place because I can't recreate it.  Is anyone else reporting
issues with quiz grading?

Thanks,
Blake

**Comment by mnichols13** [comment]
We have not had any other teachers report issues.

**Comment by dpentony** [comment]
@bguerrettaz - we probably need to follow up with the teacher before the weekend. Are you still looking into this?

**Comment by bguerrettaz** [comment]
I have tried different combinations to recreate this, which is what I would
use to debug the code and put in a possible fix, but haven't been able to
emulate it.

Have either of you been able to recreate with this teacher or any other?

Thanks,
Blake
