### ISSUE TITLE
Update SOME IL Ag subscriptions

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#199]
We are running into the issue of some IL ag subscriptions expiring on 7/1/2016. This is not correct. These must have been missed when you did the last mass update in IL. Here is what we need:

For all IL A

**Comment by dpentony** [comment]
We are running into the issue of some IL ag subscriptions expiring on 7/1/2016. This is not correct. These must have been missed when you did the last mass update in IL. Here is what we need:

For all IL AG subscriptions, we need their account expiration date to be 12/1/2017. Also, we need the expiration dates on the lessons, Eunits and CSAT for the libraries they currently have access to, to also be 12/1/2017.

Please make this a priority as we teachers are again trying to login in prep for the start of fall classes.

**Comment by bguerrettaz** [comment]
I will work on this and let you know when completed.

Blake

**Comment by bguerrettaz** [comment]
I'm not able to find any IL, Ag teachers with an active subscription with
that date as indicated.  Here are the dates I'm seeing and the number of
teachers with that date:

2017-07-01 00:00:00.000 5
2017-12-01 00:00:00.000 941
2018-07-01 00:00:00.000 23

I didn't change the date if it was past 12/01/2017 in my mass update before
because I assumed that these teachers/schools paid for the extended
subscription?

It looks like the only ones that are unique are the 5 with the 07/01/2017
date?

Please let me know how you'd like me to proceed.

Thanks,
Blake

**Comment by dpentony** [comment]
I can give you two quick examples:

Whitney Phillips at Astoria HS
Sarah Moore at Athens HS

You can see plenty of them in you go into the admin and click Edit Teachers, choose IL and a list of all teachers will display.

**Comment by bguerrettaz** [comment]
Both of those teachers are 'Inactive' in the database.

Do you want all inactive teachers to have the same deactivate dates?  When
I do these extensions, I only look for active teachers.

Blake

**Comment by dpentony** [comment]
Those teachers were not inactive prior to 7.1.16. They only became inactive when the incorrect account expiration date of 7.1.16 was reached. So I cannot understand why they were missed back when you last did the bulk update

**Comment by bguerrettaz** [comment]
I'm not sure how these were missed either.  I query I wrote caught them
now, unless something was different then about these 68 teachers.

Either way, I have corrected their dates, please test and confirm.

Thanks,
Blake
