### ISSUE TITLE
Eunits Titles not Dispaying when Assigned

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#210]
The Eunit titles for those associated with the Ag Power and Ag, Food & Natural Resources do not display when assigned. See screenshots below. These are our two newest libraries and that may have something to do with it. See also issue 93. We had this problem in the past on one library.

This is the teacher view:

![image](https://cloud.githubusercontent.com/assets/5790325/17944201/5945b99c-6a04-11e6-94c6-e99f20fb04bd.png)

This is the student view:

![image](https://cloud.githubusercontent.com/assets/5790325/17944250/8a037222-6a04-11e6-8747-59f1929f9662.png)

**Comment by bguerrettaz** [comment]
I spent some time looking into this and reviewing what had happened on
issue 93 (it appears that was never resolved).

What I've concluded is that there are old references to an old database and
table that is no longer used.  When someone imports the CSV or brings in
eUnits by other means, only the new table is updated, not this old one.  If
there are no records, then the code defaults to n/a, which is what you're
seeing.

I've made the necessary changes to two of the pages on the teacher side.
One is the course view as seen above and the other is when you select
students.

I haven't made changes to the students side yet and I'm quite sure this old
referenced table is in other spots as well.

I'm hoping you can help me identify those spots so I can correct the code.

Please test and confirm the teacher side as well as let me know where else
these new libraries' eUnit's show up as n/a, for example, the student side,
the missing file report, etc.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good on the teacher's side.

On the student side, the n/a shows up when viewing assigned Eunits. If you login as student Luke Cullan under teacher Gordon Dale Karney and look at the assigned Eunits under Ag Construction and Projects, you'll see the n/a. That is mainly where it needs to be fixed for Eunits in both the Ag Power and Ag, Food, and Natural Resources libraries.

What can we do to prevent this from happening in the future when we add new libraries?

**Comment by bguerrettaz** [comment]
I have put the fix in for the student side as well.

To answer your question on preventing this from happening, I've put code
fixes in to pull from the correct table.  The reason this was happening is
because the code was pulling from an old table and database.  I have
corrected that, so anything new will automatically be reflected going
forward.

I have fixed this in three places (two on the teacher side and one on the
student side).  I'm not sure if this code is anywhere else, so if you run
into n/a as the eUnit title again, let me know and I can correct the code
in that location.

Please test and confirm the student side.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks. We'll close for now and re-open if we run into the n/a in any other locations.

**Comment by mnichols13** [comment]
We have a new issue with E-unit titles not displaying correctly.  Dan and I thought this might relate back to this same issue.  
The new issue is with Ag Business titles not matching with the E-units.

![image](https://cloud.githubusercontent.com/assets/5790342/18319013/9b54dff8-74e9-11e6-8c57-c54c6df4e3ce.png)

![image](https://cloud.githubusercontent.com/assets/5790342/18319023/a8278cb2-74e9-11e6-9341-5412706627ae.png)

**Comment by dpentony** [comment]
@bguerrettaz - the Missing File Report on the Admin side is displaying the titles correctly and since the Agbusiness library has been around a long time without this problem, it leads us to believe the issue has something to do with the changes you made to pull from a different table. It is only showing on the user side.

**Comment by bguerrettaz** [comment]
I'm looking into this.  Couple of questions:

- Which one is correct for this example; Sole Prop. or Applying E-Commerce
in the Agribusiness?
- Are there any other libraries affected?  Could you do a few spot checks
to make sure?  The reason I ask is this could be some bad data (I'm
retrieved it from the database) or it could be a bigger problem.

Thanks,
Blake

**Comment by mnichols13** [comment]
The correct one is Sole Proprietorships
I have spot checked Horticulture, AG Power, Animal Plants and Soils - they all look ok,
It appears to only be an issue in AG Business.

**Comment by bguerrettaz** [comment]
As I was in the process of fixing this issue, something stood out to me
that didn't seem right:

[image: Inline image 1]

This is the extract from the database, where the 'code' = 060003, which is
the number of the e-unit.  But if you look at the lessonfile column and the
eunit file column, they both states 060003 for the incorrect two first rows
and 060006 for the sole proprietorships records.

Why would the codes for both match?  Since the logic is looking for the
'code' that's why we are seeing the incorrect record in the webpage.

The missing file report:

[image: Inline image 2]

Shows the same thing, 'Applying E-Commerce in the Agribusiness' is L060003
and 'Using Sole Proprietorships' is showing 'L060006', which is confusing.

The same is true for 060004:

[image: Inline image 4]

060005:

[image: Inline image 5]

And so on.

The reason I'm pointing this out is to better understand what is going on
in the data and to fix the correct problem.

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake,  Do you need anything further from us to fix this?  It sounds like you have it figured out, but I just want to confirm that you didn't need something from us to move forward.

**Comment by bguerrettaz** [comment]
Well the biggest thing is, I don't know why they have the same code as the
others, and why they have different e-unit files...that's why they are
coming up incorrectly.

Why is the code the same for sole prop. as e-commerce?

**Comment by mnichols13** [comment]
Dan, I think Rita or Tim needs to be involved on this one.  This is not my area...

**Comment by mnichols13** [comment]
Blake,
Dan & I talked, we are not able to see your images, which is making this difficult to be on the same page.  I do see that in every other library that the lesson plans, E-units and ppts all have the same file name, with a different extension.  In the ABR library they are not matching, so I agree this is the problem.  The question is how did the numbering get messed up on this one library?

**Comment by dpentony** [comment]
@bguerrettaz - please be sure you are looking at the correct Missing File Report. You want the one for Agribusiness Revise (ABR) as opposed to Agbusiness Management (AB).

**Comment by mnichols13** [comment]
E-unit titles are also an issue in AGL library - this is Bill Stowell's student account in NY
![image](https://cloud.githubusercontent.com/assets/5790342/18452344/1690d946-7900-11e6-9fc3-6bc6334946ae.png)

**Comment by bguerrettaz** [comment]
Ok, after doing more digging, I think I found the issue with the incorrect
titles and why they didn't match the missing file report.

I have put the fix in for the pages that are affected (pages with e-unit
titles that we've identified being incorrect).

Please test and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good
