### ISSUE TITLE
Eunit date changes not holding

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#215]
Marty Speth is a teacher in WI. He has Eunit 040108 assigned to students in his Botany class. He had put in dates of 9/16/2016 - 9/20/2016. When he tried to change the dates they would not stick. Instead, it would add a second instance of the Eunit assigned to that course. 

If you try to delete the existing dates and save the changes, the dates disappear but if you logout and log back in, the dates are still there. We were finally able to get the dates deleted by deleting the Eunit via the Custom Calendar under Maintain Assigned Eunits/PPTs, but the Eunit is still assigned (with no dates).

His whole page for Maintaining Assigned Eunits for the Botany course is acting strange. Look at all the Eunits he has active for the course (see below).

![image](https://cloud.githubusercontent.com/assets/5790325/18683431/e7bdd718-7f35-11e6-978f-0539dbef036f.png)

Butt none of them show up when you login as student Cristina Aranda:

![image](https://cloud.githubusercontent.com/assets/5790325/18683488/1977bae4-7f36-11e6-86c9-f3d5329f876d.png)

This is somewhat similar to  issue #84 we had back in 2014.

**Comment by bguerrettaz** [comment]
Can this issue be replicated for any one else?  Can you replicate under
your account or has anyone else brought this up?

I'm just wondering if its an actual code defect or something specific to
his account that I'll need to track down.

Blake

**Comment by dpentony** [comment]
It appears to be something associated with just the Botany course in this teacher's profile.

**Comment by bguerrettaz** [comment]
I've tried to recreate the date issue on the maintain eunits page and was
able to set the dates and then change the dates successfully.

I did check, and it appears that he doesn't have access to the eUnit
010039, if you click on that one, he'll be redirected because he doesn't
have that in his access list for libraries.

It appears that because he doesn't have access, they shouldn't be appearing
on the page, which is one of the problems.  I would also imagine that would
be why they don't show up on the student side.

Is this in line with what you are seeing as well?

**Comment by dpentony** [comment]
Yes, I agree. 

What would it take to eliminate them showing up on the assigned Eunits page if he does not have access to them? It's confusing as it is now. If the teacher does not have access to them, they should not show up on the assigned eunits page.

**Comment by bguerrettaz** [comment]
I would need to add code to account for what the teacher has access to.
Probably a few hours to get that in place.

Has anyone else had any issues with this page?

**Comment by dpentony** [comment]
I believe it is unique to his page.
