### ISSUE TITLE
Issue with alignments for TEE/IT library

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#216]
Blake,
I am trying to enter alignments for the TEE library and I cannot get them to show up.  I think this might best be explained in a phone call.  If you could call me when you are available x133  Mindy

**Comment by dpentony** [comment]
@bguerrettaz - I'd appreciate your giving Mindy a call to discuss this.

**Comment by bguerrettaz** [comment]
Yes, apologies, last week was jam packed.

Mindy - can you take a call around 3?

**Comment by mnichols13** [comment]
yes I will plan for around 3pm

**Comment by bguerrettaz** [comment]
Ok, I've searched throughout the database for the T&EE library that was
changed to IT.  I reverted anything I found that was stated as IT and
changed it to T&EE.

I also found two individual lessons there were prefaced with IT, instead of
T&EE, I corrected that as well.

Please test all of this and confirm it looks correct.  If you find any
other instances, please let me know and I'll work to fix.

Thanks,
Blake

**Comment by mnichols13** [comment]
This looks good.  I was able to align the standards and everything shows up.  Thanks!
