### ISSUE TITLE
Deleting Questions from Quiz

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#221]
Jeni O'Connor of Libertyville cannot delete questions from the quiz "(O'Connor) 8th Grade Quiz #1 Biotech & FFA Basics". I was able to replicate in both Mozilla and Chrome. She cannot delete questions from the end of the quiz, but can from the beginning. 

![oconner quiz](https://cloud.githubusercontent.com/assets/21039374/19694747/2a14a3ae-9aa6-11e6-8bf2-124445716020.JPG)
![oconnor questions](https://cloud.githubusercontent.com/assets/21039374/19698260/32be2828-9ab4-11e6-8e83-4fcb218b4cb6.JPG)

**Comment by bguerrettaz** [comment]
I'm looking into this issue.

**Comment by dpentony** [comment]
As you research this, you should know that the teacher edits practically every question. I am wondering if the fact that she does so has an impact on her ability to delete certain questions.

**Comment by bguerrettaz** [comment]
I was finally able to hunt down what the issue was, there was a generated
piece of JavaScript code that wasn't escaping the single quotes correctly.
Since O'Connor was in some of the quiz names, that was part of the problem.

This has been fixed and I have tested the ability to delete questions.

Please test and confirm.

Blake

**Comment by knovotney** [comment]
Thanks, Blake. She has not responded, but we will close for now.
