### ISSUE TITLE
Assigned PPTs not opening - URGENT

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#239]
Melissa Wolters is a teacher in IN. She assigned 46 PPTs for her IN ALS Animals /spring 2017 Block I course. If you log in as a student in that course (ex. Blake Alig), you can see the 46 PPTs, but when you attempt to open them, the following error message appears. Please advise.

ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/authenticationCheck.asp, line 110

**Comment by bguerrettaz** [comment]
This issue is related to how the files are named and how they are looked up
in the database.  Most PPT's seem to start with 'P' and a set of numbers.
These are like so: ALSA_C-4.ppt.

I had to write code to account for those, seemed these were missed in prior
tests we ran.

Please test and confirm the fix.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks for fixing. Why would this be an issue now when we have had those PPTs out there for 5+ years? I vaguely recall this issue cropping up some years ago.

**Comment by bguerrettaz** [comment]
This actually needed to be accounted for in the new authentication check
code (for PPT's, eUnits, etc.).  This must've been missed in testing, since
we didn't find the error until now.

It was due to how these certain one's were named.

Thanks,
Blake
