### ISSUE TITLE
New Jersey missing under drop down box - Please add state! 

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#249]
When I try and add a CTE teacher for New Jersey, on the page where I add the state - NJ is missing.  I start with the National state and then on the second page where I add the state, school name, teacher name, etc - New Jersey does not exist.  

Teacher wanting trial - how quick can this be added?

**Comment by bguerrettaz** [comment]
The reason New Jersey isn't showing up in the list is because there is a
table tblNationalUser that houses the list of teachers and their respective
school.  Since the state list is dynamic from this table and since this
table doesn't currently have any user associated with NJ, that state isn't
an option.

My guess would be that I would have to manually insert a record for this
teacher, put his state as NJ and then you would see that in the list.

Could you add the teacher as a regular user, and then we can edit the
teacher after I insert it manually into that table?  I'm not sure why it
was designed this way, this is just the way the current code reads.

Let me know how you'd like to proceed.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
There wasn't ever an answer to my reply on this issue.  Can you please review and let me know thoughts?

Thanks,
Blake

**Comment by dpentony** [comment]
Mindy is on vacation this week. She and I will discuss this when she gets back.

**Comment by mnichols13** [comment]
Could you clarify what you mean by  "add as a regular user"   I am assuming this means add the teacher under the state of New Jersey as we would an AG teacher.

**Comment by knovotney** [comment]
@BrianPeterlin @bguerrettaz This issue needs to be resolved. We need to be able to add CTE teachers to National State--> New Jersey. 

If we add them under the state of NJ it does not allow them to access ANY of the materials.

**Comment by bguerrettaz** [comment]
This issue is now resolved.  Please test and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
Tested - looks good
