### ISSUE TITLE
Trouble entering test questions

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#265]
I am trying to enter test questions for our new library Next Generation Plant Science, I cannot get the "ADD QUESTION"  button to work in CHROME

I tried to enter them in Firefox and the pop box won't work in Firefox - I use the control V function and enter into the box so it strips all the code from Microsoft word.   

So then I just entered them without using control V and it added in a ridiculous amount of space and I cannot get it deleted.  If you go into the NGPS questions for the first lesson plan you can see what it looks like if you arrow down several pages.    

![image](https://user-images.githubusercontent.com/5790342/34686529-76e7c974-f471-11e7-933e-515ccd22d2bd.png)

**Comment by mnichols13** [comment]
![image](https://user-images.githubusercontent.com/5790342/34686550-9463dfe2-f471-11e7-8940-0e06dcf87617.png)

**Comment by mnichols13** [comment]
This is how it displays in Firefox when I enter into the box in the above comment:

![image](https://user-images.githubusercontent.com/5790342/34686637-d91b395a-f471-11e7-85f8-f38927e8144a.png)

**Comment by mnichols13** [comment]
any update on this?

**Comment by bguerrettaz** [comment]
Yes, after doing some research and testing with this last night and today,
I have found that when you copy text (or anything) out of an Office product
(Word, Excel, etc.), you also copy formatting attributes in the form of
XML.  That XML formatting code, plus the text you are trying to copy are
then placed into the editor, which contains code that messes with the
actual add/edit question page.

I tested different scenarios, the copy out of Word or Excel caused this
problem, then I copied out of Word and placed it in notepad, that removed
the formatting, you can then copy out of notepad into the editor and it is
correct.

I had to delete the questions you placed in there because essentially they
were corrupted data entries with that Word formatting.

So the legitimate ways to build questions in this editor is by typing in
the text box, or copying out of a plain text editor, not Word or Excel.
Again, if you have anything in Word/Excel that you want in a question,
paste it in Notepad first, then re-copy in Notepad, then paste in the
editor to strip away the formatting stuff.

Please let me know if you have any questions.

Thanks,
Blake

**Comment by mnichols13** [comment]
yes I agree with all of that, but when I tried to enter into the text box I could not get the ADD Question button to work..  I guess I should have left the rest of the discussion out.

**Comment by dpentony** [comment]
@bguerrettaz  - we just want to make sure you understand the issue. The ADD Question button does not work. We've got lots of questions to add and are hoping you can address it this evening.

**Comment by bguerrettaz** [comment]
It doesn’t work when you copy from Word, at least with my testing, but does work with my other tests.

Could you try again and if it doesn’t work walk me through the scenario?

Thanks,
Blake

**Comment by mnichols13** [comment]
sent you a email to your gmail address with screen shots step by step

**Comment by mnichols13** [comment]
I cannot get this to work no matter what I do.  The submit button works when I copy into NOTEPAD and it looks like the question submits, but nothing is there when I go to proof it.  I am at a loss.  Blake can you tell me how you got it to work?  Were you on a MAC?  What browser?  etc..

**Comment by dpentony** [comment]
Blake, can you call Mindy and walk her through how you were able to successfully do it? -  217.446.0500, ext. 133. If we cannot get it to work for Mindy, what other editor products are viable? We have a definite need to be able to enter a lot of questions in an efficient manner.

**Comment by bguerrettaz** [comment]
Yes, I can call you and walk you through it, I might have some time
tomorrow before noon, maybe around 10am?

**Comment by mnichols13** [comment]
That sounds fine to me.  thanks

**Comment by bguerrettaz** [comment]
I actually need to push it until 10:30, does that time work?

**Comment by mnichols13** [comment]
yes, I will plan for that

**Comment by bguerrettaz** [comment]
Hi Mindy,

I deleted all of the questions under that lesson, most were us just testing.

I did some initial testing.  The key is to first paste the question from
wherever you're getting it from into Notepad, then copy from there into the
editor in Firefox.  This worked for me.

It did not work in Chrome.

Please mess with it and let me know what you find.

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake & Dan, 
It seems to work in Firefox by copying and pasting the original document into Notepad first.   Thanks for your work on this.

**Comment by dpentony** [comment]
@BrianPeterlin -  We'd still be interested in looking at a new editor which would allow us to paste questions directly from Word as we used to be able to do. Please let us know if you identify any.
