### ISSUE TITLE
Student Test Views Not Recorded

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#274]
Mary Clements is a student at the Horticulture EOP School in South Carolina. Today, they were giving a statewide end of pathway exam for hort students. The teacher name in SC is "State Staff" at the Horticulture EOP  School. The name of the test is Hort EOP 2017-2018. She got kicked out but only completed about 80 of 100 questions. She saved her progress as she progressed through the test.

After getting kicked out, she is unable to access the test again. However if you go to View Student Submissions under the Edit Quiz link, Mary Clements does not even show as having viewed the quiz. We wanted to wipe out her views so she could finish the quiz. But we cannot wipe out her views because none show up even though we know she completed about 80% of the test. 

Why aren't her views showing up under student views for this test? 

This happened to a couple other students who took the statewide tests last week,

**Comment by bguerrettaz** [comment]
Hi Dan,

I researched this issue a bit and can't seem to make it happen again.  Here is the data I found for this student on this test:

![image](https://user-images.githubusercontent.com/5695475/39938477-b0eebbe8-5518-11e8-885c-ec2fce6ed878.png)

I also checked all of the submissions and nothing shows.

As you can see from the data, the test was viewed 7 times by Mary.  The number of views on that test is set to 1, could that be one of the issues?  Also, it was set to go inactive or only be viewable until May 9th, which was the same day this occurred it seems.

Since I can't make this happen again, I'm struggling with how to diagnose or fix.  Let me know your thoughts.

Thanks,
Blake

**Comment by dpentony** [comment]
Blake, what's odd is that her views do not show up under MY Quizzes>Edit Test>Views. Mary Clements is not listed among the students who have viewed the test. Nor does it show that she submitted it.

Do why do her views show up in your report but not the one we routinely look at?

![image](https://user-images.githubusercontent.com/5790325/39939040-9496a562-551a-11e8-879a-5cc448e3a678.png)

**Comment by bguerrettaz** [comment]
Hi Dan - I've finally found out why Mary's wasn't showing in this list.  I
have corrected the issue.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks. I can now see her views in the report we always look at. I'm not sure how to test, but I think we can close it out. With her now showing up in the views, we could wipe them out so that she could have finished the test.
