### ISSUE TITLE
Wrong ppt files show up for students

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#294]
Dawn Jones, IL teacher has assigned ppts from her Foods 2 course.   When you look at the ppts from the course outline page everything looks fine.  When the students try to open them from their page - the wrong ppt opens.  

CA C8-3 Butter Cakes - 700006 instead of 700136
CA C8-5 Custard and Puddings 700007 instead of 700141

Here is what shows up on the student page

![image](https://user-images.githubusercontent.com/5790342/65911878-ecdabf80-e392-11e9-85cf-99f45210323d.png)
 instead of what shows up on our missing file report page
![image](https://user-images.githubusercontent.com/5790342/65911933-067c0700-e393-11e9-9fb1-60f82f36ccde.png)

**Comment by dpentony** [comment]
I spoke with Tim on this. We tried to delete the old PPT file on the Admin site under Maintain Files>> Delete PPTs. We did it only for lesson CA:C8-3. and were able to delete the old PPT file (P700006). However, that file still shows up when you login as a student in the Foods 2 course. The file still shows up, but if you click on it, you can't get to it. Regardless, the PPT file that should be showing up for the lesson is the one listed in the Missing File report (P700136)

**Comment by bguerrettaz** [comment]
Ok, took a bit to track this down, but I think I had some information.  For
CA:C8-3, this was in the database:
[image: image.png]
I believe this needs manually changed to the correct PPT.  The teacher side
gets the information in a totally different way (no idea why), so that
explains why they don't match.  Let me know if I should manually change the
PPT column to represent P700136.ppt instead.

For CA:C8-5, here is what's in the database:
[image: image.png]

The code is grabbing the first record, which is the incorrect one.  I'm
assuming there shouldn't be duplicates of this.  My fix here would be to
manually remove the first entry and leave the second.

Please let me know how to proceed.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Hi - I think I addressed this in my last message, I'll look for your reply
on that.

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake - please do that and we'll check to see if this corrects the problem.

**Comment by bguerrettaz** [comment]
I have made the appropriate changes.  Please test and confirm this fixes
the issues.

Thanks,
Blake

**Comment by mnichols13** [comment]
I logged in as one of Dawn Jones' students and tried to see the ppts assigned and got this.
![image](https://user-images.githubusercontent.com/5790342/66060910-0ea78400-e504-11e9-9a58-5b90dc5ad7fe.png)

**Comment by bguerrettaz** [comment]
Sorry, had that one to research, its off now.

**Comment by mnichols13** [comment]
It looks good to me, I want to give the teacher a chance to take a look before I close it.
