### ISSUE TITLE
Performance Load Time of Saved Course Outline

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#308]
see if the new google classroom button is slowing down the load time of the saved course outline page

**Comment by bguerrettaz** [comment]
Here is the analysis that I did...it does appear that the new Google Share is causing a significant slowdown:

Without: ~4 seconds 

![image](https://user-images.githubusercontent.com/5695475/88201245-d7c66a00-cc0c-11ea-86d9-14676e8d0965.png)

With: ~15 seconds 

![image](https://user-images.githubusercontent.com/5695475/88201311-e90f7680-cc0c-11ea-93c0-9f1bf6100276.png)

I'll need to look at a different design to get away from this performance issue.  It only happens with long course outlines because the original code processes items 1 by 1 and over and over again.  It's less of an issue with smaller course outlines.

Question: should I remove for now until I get the new design out?

**Comment by dpentony** [comment]
Depends. How long will it take to get the new design out?

**Comment by bguerrettaz** [comment]
I'm actually not sure yet...I'll have to get creative with how to implement
this and not have performance concerns.  I'll see what I can do and let you
know a timeline.

Blake

**Comment by dpentony** [comment]
Were you ever able to look at a timeline for this item?

**Comment by bguerrettaz** [comment]
I'm actually hoping to have a solution mid this week...been testing a few
different designs.

**Comment by bguerrettaz** [comment]
Hi - I've implemented a new design for the Google Share.  I've timed both
without share completely and with this new design and there are only
marginal differences.  Can you please test and confirm the same?

Thanks,
Blake

**Comment by DouglasFalk** [comment]
Doug Falk set up courses today.  I felt like the website had sped up.  Thank you.  I will say Teachers Love the Google Share.  Thank you.

**Comment by bguerrettaz** [comment]
Awesome, glad to hear.  Thanks

**Comment by mnichols13** [comment]
fix looks good on this
