### ISSUE TITLE
Pop-Up to notify teachers

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#326]
need requirements on query to able target teachers

**Comment by dpentony** [comment]
We're looking for a system where we could create customized pop-ups to certain teachers. We'd need to be able to filter who would see such messages. Filters might include: 

1. State
2. Type of teacher (Ag or CTE)
3. Libraries they subscribe to
4. Expiration date

**Comment by bguerrettaz** [comment]
Thanks - so this would be on the admin side, you would need an interface,
filterable queries and a mechanism to have a dynamic popup, is that
correct?  Here is the breakdown estimate for that work:

- Interface on admin side - 6-10 hours
- Filterable queries - 5-6 hours
- Creation of dynamic popup after login for selected users - 4-6 hours

Total: 15-22 hours

Thanks,
Blake

**Comment by dpentony** [comment]
Your understanding is correct at this point. We may also want a filter to set how long/how often the pop-up would appear.

I'll share the estimate with our board and be in touch.

**Comment by bguerrettaz** [comment]
Sounds good - thanks Dan

**Comment by dpentony** [comment]
We would like to move forward on this in order to have it ready come early January. Do we need to schedule a phone call to discuss it?

In addition to the above filtering specs, is there a way we could set how many times the teacher would see the pop-up?

**Comment by BrianPeterlin** [comment]
@bguerrettaz, need an update

**Comment by bguerrettaz** [comment]
I should have this ready to test before the end of the month.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Sorry, one more point on your questions about controlling how many times a
teacher sees a specific popup, this will be a bit more involved as we would
then have to log each time the message is shown, by teacher.  My suggestion
would be to implement the original scope and then add that on soon
thereafter.  Thoughts?

**Comment by dpentony** [comment]
@bguerrettaz - instead of controlling the number of times a teacher sees the message, could we integrate a date range "control" where we could set the dates the pop-up would be visible?

**Comment by bguerrettaz** [comment]
Yes, that can definitely be included.

**Comment by bguerrettaz** [comment]
Happy New Year!  The add popup interface, logic and database work is near
completion and ready for your testing.

Once you login to the admin site, please go to this URL:
https://mycaert.com/admin/Content/AddTeacherPopup.asp

You have to visit that URL as I don't have links on the left navigation bar
yet.

You can test creating a popup through this interface.  Please note, at this
time, the only teacherID that will show this new popup functionality is
Dan's Ag account (394).  If you'd like more added, please let me know their
ID's and I can add that to the test code as well.

Please let me know if you have any questions or if you find any issues.

Thanks,
Blake

**Comment by dpentony** [comment]
@bguerrettaz  - I created a pop-up for myself and was able to see it. However, I'd like a few of us to test it further.

Could you please add the following accounts so they can see any pop-ups created?

Mindy Nichols IL  Ag Account:
UN = mindyAG
PW = love2work

Doug Falk IL Ag Account:
UN = DFalk
PW = tori

Mindy McDermott Il Ag Account:
UN = MMcDermott
PW = mindy

**Comment by bguerrettaz** [comment]
Thanks Dan - these three accounts were also added.

Thanks,
Blake

**Comment by dpentony** [comment]
@bguerrettaz - I could have sworn I posted the comments below last week. There were not there today when I checked. Please let us know what is possible.

1.	Can the actual box with the pop-up message be made more attractive/prominent and could it be positioned more towards the center of the page? We view this functionality more as a targeted marketing tool and we would like it be visually attractive and centered towards the middle of the page. Ideally, we would like the ability to change fonts/type sizes and colors, and have the ability to include links.

2.	After selecting the teachers, there needs to be a “Select All” link. 

3.	Will there be a link so that Admin can review/edit/delete pop-ups already created?

4.	Sort by column does not seem to work. We chose Ag teachers in Illinois and then sorted by Teacher Name. The list that comes up is for all teachers in Illinois – both Ag and CTE. 

5.	Can a filter be added to select teachers in a state by Active/Inactive status in addition to Focus? For instance, we would like to send a message to only IL Ag teachers that are active. We were only able to pull up all IL Ag accounts - both active and inactive.

**Comment by bguerrettaz** [comment]
Hi Dan, please see my comments below.  As far as priority, are these
changes or the enhanced reports a higher priority?

Thanks,
Blake

On Tue, Jan 12, 2021 at 10:30 AM dpentony <notifications@github.com> wrote:

> @bguerrettaz <https://github.com/bguerrettaz> - I could have sworn I
> posted the comments below last week. There were not there today when I
> checked. Please let us know what is possible.
>
>    1.
>
>    Can the actual box with the pop-up message be made more
>    attractive/prominent and could it be positioned more towards the center of
>    the page? We view this functionality more as a targeted marketing tool and
>    we would like it be visually attractive and centered towards the middle of
>    the page. Ideally, we would like the ability to change fonts/type sizes and
>    colors, and have the ability to include links.
>
> My initial estimates were for a 'normal' message popup.  To incorporate a
dynamic/editable textbox will take me some more time.  Please let me know
if you'd like to go that direction.  I cannot change where the current
popup comes up on the screen as that's controlled by the browser.

>
>    1.
>
>    After selecting the teachers, there needs to be a “Select All” link.
>
> I can add this in

>
>    1.
>
>    Will there be a link so that Admin can review/edit/delete pop-ups
>    already created?
>
> I did not incorporate an edit (I envisioned this as being a utility to
send alerts or expirations, etc....maybe this was my miss).

**Comment by dpentony** [comment]
See my comments IN ALL CAPS BELOW

1. As far as priority, are these
changes or the enhanced reports a higher priority? **COULD YOU HAVE ENHANCED REPORTS DONE BY JANUARY 25 AND THESE ADDED POP-UP FUNCTIONALITY READY IN EARLY FEBRUARY? WE DEFINITELY NEED ENHANCED REPORTS BEFORE OUR BOARD MEETS WITH ISBE ON JANUARY 27.**

  2.  Can the actual box with the pop-up message be made more
    attractive/prominent and could it be positioned more towards the center of
    the page? We view this functionality more as a targeted marketing tool and
    we would like it be visually attractive and centered towards the middle of
    the page. Ideally, we would like the ability to change fonts/type sizes and
    colors, and have the ability to include links.

 My initial estimates were for a 'normal' message popup.  To incorporate a
dynamic/editable textbox will take me some more time.  Please let me know
if you'd like to go that direction.  I cannot change where the current
popup comes up on the screen as that's controlled by the browser. - **HOW MANY ADDITIONAL HOURS WOULD THIS TAKE?**

3. After selecting the teachers, there needs to be a “Select All” link.

 I can add this in - **PLEASE PROCEED.**

4. Will there be a link so that Admin can review/edit/delete pop-ups
    already created?

 I did not incorporate an edit (I envisioned this as being a utility to
send alerts or expirations, etc....maybe this was my miss). **WE NEED THIS FUNCTIONALITY TO BE ABLE TO CALL BACK/EDIT/REVISE A POP-UP MESSAGE. PLEASE PROVIDE TIME ESTIMATE.**

**Comment by bguerrettaz** [comment]
Hi Dan, please see my comments to your questions in green below.

Blake

On Wed, Jan 13, 2021 at 9:56 AM dpentony <notifications@github.com> wrote:

> See my comments IN ALL CAPS BELOW
>
>    1.
>
>    As far as priority, are these
>    changes or the enhanced reports a higher priority? *COULD YOU HAVE
>    ENHANCED REPORTS DONE BY JANUARY 25 AND THESE ADDED POP-UP FUNCTIONALITY
>    READY IN EARLY FEBRUARY? WE DEFINITELY NEED ENHANCED REPORTS BEFORE OUR
>    BOARD MEETS WITH ISBE ON JANUARY 27.*
>
> Yes, my goal is to have the reports (as requested, without any of the
enhancements you just referenced in your latest email, by January 25th).  I
can then pivot to enhance this popup functionality.

>
>    1.
>
>    Can the actual box with the pop-up message be made more
>    attractive/prominent and could it be positioned more towards the
>    center of
>    the page? We view this functionality more as a targeted marketing tool
>    and
>    we would like it be visually attractive and centered towards the
>    middle of
>    the page. Ideally, we would like the ability to change fonts/type
>    sizes and
>    colors, and have the ability to include links.
>
> My initial estimates were for a 'normal' message popup. To incorporate a
> dynamic/editable textbox will take me some more time. Please let me know
> if you'd like to go that direction. I cannot change where the current
> popup comes up on the screen as that's controlled by the browser. - *HOW
> MANY ADDITIONAL HOURS WOULD THIS TAKE?*
>
I'll actually need to see what enhanced popups are available and run
options by you.  I'll most like use jQuery for that, but that will also
require an enhanced text box to give you more formatting options for the
messages, etc.   Something like this?
https://jqueryui.com/dialog/#modal-message
I would assume this would take an additional 6-10 because both the
front-end interface and the backend editor would need to account for this
enhanced style of dialog messages.

>
>    1. After selecting the teachers, there needs to be a “Select All” link.
>
> I can add this in - *PLEASE PROCEED.*
>
Ok

>
>    1. Will there be a link so that Admin can review/edit/delete pop-ups
>    already created?
>
> I did not incorporate an edit (I envisioned this as being a utility to
> send alerts or expirations, etc....maybe this was my miss). *WE NEED THIS
> FUNCTIONALITY TO BE ABLE TO CALL BACK/EDIT/REVISE A POP-UP MESSAGE. PLEASE
> PROVIDE TIME ESTIMATE.*
>
To be able to edit, delete and maintain these popups, I would estimate 5-8
hours (this would include the enhanced textbox editor that I mentioned
above, if you choose to proceed).

**Comment by dpentony** [comment]
Let's put this on hold for now. Please concentrate on the Enhanced Reports. We'll circle back to this once the enhanced report are finished.

**Comment by bguerrettaz** [comment]
Sounds good - thanks.

**Comment by dpentony** [comment]
I'd like to circle back to this and get a firm estimate on the additional time involved in:

1. Can the actual box with the pop-up message be made more
    attractive/prominent and could it be positioned more towards the
    center of
    the page? We view this functionality more as a targeted marketing tool
    and
    we would like it be visually attractive and centered towards the
    middle of
    the page. Ideally, we would like the ability to change fonts/type
    sizes and
    colors, and have the ability to include links.

2. A link so that Admin can review/edit/delete pop-ups
    already created?

**Comment by BrianPeterlin** [comment]
@bguerrettaz , can you respond to these with an estimate on hours?

**Comment by bguerrettaz** [comment]
12-18 hours for both items.

Thanks,
Blake
