### ISSUE TITLE
Google SSO

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#334]
Google SSO is not working

Steps to recreate
Open Chrome in Incognito
goto MyCaert.com
Select Students Login
Select Google Sign In
Login to your Google Account

I have this account setup as peterlin3@gmail.com

It does not redirect to The Student Landing Page

![image](https://user-images.githubusercontent.com/5776485/110250024-d731d800-7f3e-11eb-83d5-46991f7fa731.png)

**Comment by bguerrettaz** [comment]
I'm not sure what is causing this for you.  I followed your steps and
logged in with my account and it worked correctly.  I also tested the
normal automation SSO/sign in which also worked correctly.

Can anyone else confirm this issue with your account?  @Brian Peterlin
<bpeterlin@cmiti.com> - can you try it with a different account?

Thanks,
Blake

**Comment by BrianPeterlin** [comment]
you can try using this google account

bpeterlin@tcsea.org

I will txt you the password

**Comment by BrianPeterlin** [comment]
I just tried in Microsoft Edge and it worked, so it is a cache issue

I did clear cache in Cloudflare too

**Comment by BrianPeterlin** [comment]
I did not this, if you goto this link https://www.mycaert.com/default.asp?Confirm=LogOut

and click on Student Login, the GMail signin is not available

**Comment by bguerrettaz** [comment]
This was actually on purpose, otherwise you'd have an infinite loop.  For
example, the way Google SSO works, if you're authenticated to Google and
logout of MyCaert, it will pick up that authentication immediately after
logout and log you back in.

The way around this was to not enable Google SSO for that specific query
string.

Thanks,
Blake
