### ISSUE TITLE
Student emails not showing up in teacher account

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#411]
Sophie Voris (teacher at McDowell High School in NC) has set up her students in MyCAERT using Gmails.
However, not all of her students emails are appearing on the "Edit Student" page. (see screenshot)
When I go into edit a student, like Rebekah Dalton, whose email doesn't seem to be entered, her email appears when I click on her name. (see screenshot). This is preventing her from being able to login with Google Single Sign-On.

Can you please provide an estimate on how long it will take to get this fixed? Needs attention ASAP. 
Thank you!

![Screenshot 2024-11-05 at 10 05 54 AM](https://github.com/user-attachments/assets/5d3c7c91-34f5-41f2-8c33-f13cf8201436)
![Screenshot 2024-11-05 at 10 05 43 AM](https://github.com/user-attachments/assets/ce2475ae-3ccf-4b17-9758-1c8d526332ea)

**Comment by LKocher** [comment]
We need a fix on this. @bguerrettaz @BrianPeterlin

**Comment by bguerrettaz** [comment]
I've investigated this and there are a couple of issues:
- The classroom email on the edit student page is a different email field from the database because the google enabled email is a different field with a different function
Here are the two different fields in the database:
<img width="146" alt="image" src="https://github.com/user-attachments/assets/b0915735-2c89-4e73-95f6-59f47a679396">
As you can see some of these are blank, matching the edit students page.

Here is the google email field used for single sign-on into Google apps:
<img width="144" alt="image" src="https://github.com/user-attachments/assets/6b6d183e-39a3-43b7-b79d-902727c0a5cf">


You can see that all of these emails are mcsgmail.com instead of gmail.com which means they likely won't work with single sign-on.  There is some setup they must have enabled on their end to enable single sign-on with these accounts but I'm not familiar with what those are and how their administrators/IT area would make those changes.

So at this time, there is nothing incorrect with this setup/functionality on our end.

**Comment by mnichols13** [comment]
@bguerrettaz This doesn't seem to make a lot of sense due to the fact that it is working for some students but not all.   Are you suggesting that the set is different for some students on their end?

**Comment by bguerrettaz** [comment]
I'm wondering if some of them are configured differently?  Since some of
them work correctly, its not our integration with Google SSO (that and we
haven't heard of issues with other students either).

I'm not sure what else we can do on our end as I can't see or change their
Google configuration and I can't test with their specific Google accounts
as I would have to be authenticated with them.

Blake
